const consoleName = {
  MAGNAVOX_ODYSSEY: "Magnavox Odyssey",
  PONG: "Pong",
  PHILIPS_TELE_SPIEL: "Philips Tele-Spiel",
  COLECO_TELSTAR: "Coleco Telstar",
  TELEJOGO: "Telejogo",
  COLOR_TV_GAME: "Color TV Game",
  TELEJOGO_II: "Telejogo II",
  FAIRCHILD_CHANNEL_F: "Fairchild Channel F",
  RCA_STUDIO_II: "RCA Studio II",
  ATARI_2600: "Atari 2600",
  BALLY_ASTROCADE: "Bally Astrocade",
  INTERTON_VC_4000: "Interton VC 4000",
  MAGNAVOX_ODYSSEY2: "Magnavox Odyssey²",
  MICROVISION: "Microvision",
  GAME_WATCH: "Game & Watch",
  INTELLIVISION: "Intellivision",
  PLAYCABLE: "PlayCable",
  VTECH_CREATIVISION: "VTech CreatiVision",
  EPOCH_CASSETTE_VISION: "Epoch Cassette Vision",
  COLECO_GEMINI: "Coleco Gemini",
  ARCADIA_2001: "Arcadia 2001 ",
  ATARI_5200: "Atari 5200",
  COLECOVISION: "ColecoVision",
  COMMODORE_MAX_MACHINE: "Commodore MAX Machine",
  ENTEX_ADVENTURE_VISION: "Entex Adventure Vision",
  VECTREX: "Vectrex",
  SEGA_SG_1000: "Sega SG-1000",
  ATARI: "Atari",
  NES_FAMICOM: "NES/Famicom",
  MSX: "MSX",
  CASIO_PV_100: "Casio PV-1000",
  ATARI_7800: "Atari 7800",
  ACTION_MAX: "Action Max",
  MASTER_SYSTEM: "Master System",
  DYNAVISION: "Dynavision",
  GAME_BOY: "Game Boy",
  GAME_GEAR: "Game Gear",
  COMMODORE_64G: "Commodore 64GS",
  TURBOGRAFX_16: "TurboGrafx-16",
  MEGA_DRIVE_GENESIS: "Mega Drive/Genesis",
  ATARI_LYNX: "Atari Lynx",
  TURBOEXPRESS: "TurboExpress",
  NEO_GEO: "Neo-Geo",
  SUPER_NINTENDO: "Super Nintendo/Super Famicom",
  COMMODORE: "Commodore",
  SEGA_CD: "Sega CD",
  CD_I: "CD-i",
  SUPERVISION: "Supervision",
  MEGA_DUCK: "Mega Duck",
  SEGA_32X: "Sega 32X",
  NEO_GEO_CD: "Neo-Geo CD",
  SUPER_GAME_BOY: "Super Game Boy",
  SATELLAVIEW: "Satellaview",
  TRES_DO: "3DO",
  AMIGA_CD32: "Amiga CD32",
  FM_TOWNS_MARTY: "FM Towns Marty",
  PIONEER_LASERACTIVE: "Pioneer LaserActive",
  ATARI_JAGUAR: "Atari Jaguar",
  PC_FX: "PC-FX",
  PLAYDIA: "Playdia",
  SEGA_SATURN: "Sega Saturn",
  PLAYSTATION: "PlayStation",
  VIRTUAL_BOY: "Virtual Boy",
  CASIO_LOOPY: "Casio Loopy",
  R_ZONE: "R-Zone",
  ATARI_JAGUAR_CD_PRO: "Atari Jaguar CD Pro",
  APPLE_PIPPIN: "Apple Pippin",
  NINTENDO_64: "Nintendo 64",
  GAME_COM: "Game.com",
  NEO_GEO_POCKET: "Neo Geo Pocket",
  GAME_BOY_COLOR: "Game Boy Color",
  POCKETSTATION: "PocketStation",
  NINTENDO_64DD: "Nintendo 64DD",
  DREAMCAST: "Dreamcast",
  NEO_GEO_POCKET_COLOR: "Neo Geo Pocket Color",
  WONDERSWAN_COLOR: "WonderSwan/WonderSwan Color",
  PLAYSTATION2: "PlayStation 2",
  POKÉMON_MINI: "Pokémon mini",
  GAME_BOY_ADVANCE: "Game Boy Advance",
  GP32: "GP32",
  XBOX: "Xbox",
  NINTENDO_GAMECUBE: "Nintendo GameCube",
  SWANCRYSTAL: "SwanCrystal",
  GAMEKING: "GameKing",
  N_GAGE: "N-Gage",
  PSX: "PSX",
  IQUE_PLAYER: "iQue Player",
  TAPWAVE_ZODIAC: "Tapwave Zodiac",
  ATARI_FLASHBACK: "Atari Flashback",
  NINTENDO_DS: "Nintendo DS",
  PSP: "PSP",
  GIZMONDO: "Gizmondo",
  GP2X: "GP2X",
  XBOX_360: "Xbox 360",
  HYPERSCAN: "HyperScan",
  PLAYSTATION3: "PlayStation 3",
  WII: "Wii",
  VII: "Vii",
  N_GAGE20: "N-Gage 2.0",
  NINTENDO_DSI: "Nintendo DSi",
  GP2X_WIZ: "GP2X Wiz",
  DINGOO: "Dingoo",
  ZEEBO: "Zeebo",
  ONLIVE: "OnLive",
  PANDORA: "Pandora",
  NINTENDO_3DS: "Nintendo 3DS",
  PLAYSTATION_VITA: "PlayStation Vita",
  NINTENDO_WII_U: "Nintendo Wii U",
  NEO_GEO_X: "Neo Geo X ",
  OUYA: "Ouya",
  SHIELD_PORTABLE: "Shield Portable",
  PLAYSTATION4: "PlayStation 4",
  XBOX_ONE: "Xbox One",
  NINTENDO_SWITCH: "Nintendo Switch",
  XBOX_SERIES_X_S: "Xbox Series X/S",
  PLAYSTATION5: "PlayStation 5",
  ATARI_VCS: "Atari VCS",
  PLAYDATE: "Playdate"
};

module.exports = { consoleName };
